### ISSUE TITLE
Add 'gatesgarth' to the layers compatibility list please?

### ISSUE THREAD

**Issue by RossiSoftLtd** [OpenDDS/meta-opendds#12]
Hello,

Just wanted to confirm that I was able to fully configure and integrate **branch-DDS-3.16** using Yocto version **gatesgarth** without any issue.

I was therefore wondering whether it would be possible to upgrade the **conf/layer.conf** by adding such version to the LAYERSERIES_COMPAT_opendds-layer variable please.

Many thanks.

Kind regards
Eddy

**Comment by mitza-oci** [comment]
Please use a pull request to suggest changes

**Comment by RossiSoftLtd** [comment]
Hello,

been trying to do a pull request using the new 2FA authentication that requires tokens instead of passwords, but I got permission denied to access oci-labs/meta-opendds.git

Regards
Eddy

**Comment by mitza-oci** [comment]
Please see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork and if there are still issues let us know what command you ran that resulted in "permission denied."

**Comment by vermaete** [comment]
@mitza-oci 

The Yocto release 'Gatesgarth' is [End Of Life](https://wiki.yoctoproject.org/wiki/Releases).
The access to github to send PR seems to be ok.

Close this issue?
