### ISSUE TITLE
Issue while running subscriber, publisher running on Qemu with yocto opendds recipe (opendds 3.20, ACE 7.0.8)

### ISSUE THREAD

**Issue by madhugit2022** [OpenDDS/meta-opendds#19]
./subscriber -DCPSConfigFile rtps.ini  -DCPSDebugLevel 10
(383|383) INFO: set_DCPS_debug_level: set to 10
(383|383) NOTICE: Service_Participant::get_domain_participant_factory Going to load configuration from <rtps.ini>
(383|383) NOTICE: using DCPSDebugLevel value from command option (overrides value if it's in config file)
(383|383) NOTICE: Service_Participant::load_domain_ranges(): config does not have a [DomainRange] section.
(383|383) NOTICE: TransportRegistry::load_transport_templates(): config does not have a [transport_template] section.

I get the error when I ran Qemu. yocto compiled opendds. The same worked fine on Linux though(compiled on linux , 3.20) 
tried adding domain range 2 to 40 and get the below errors. 

Qemu gets a local ip. 

(384|384) INFO: set_DCPS_debug_level: set to 10
(384|384) NOTICE: Service_Participant::get_domain_participant_factory Going to load configuration from <rtps_sub.ini>
(384|384) NOTICE: using DCPSDebugLevel value from command option (overrides value if it's in config file)
(384|384) NOTICE: Service_Participant::load_domain_ranges(): config has DomainRange sections.
(384|384) Service_Participant::parse_domain_range(): (384|384) [DomainRange/2-40]: range_start == 2
(384|384) Service_Participant::parse_domain_range(): (384|384) [DomainRange/2-40]: range_end == 40

any leads are appreciated

**Comment by madhugit2022** [comment]
#qemu #yocto #opendds

**Comment by jwillemsen** [comment]
I only see notice messages, no errors

**Comment by madhugit2022** [comment]
Hi @jwillemsen 
Thanks for your response. Unlike the subscriber, publisher which runs and prints the messages and exits, this gets stuck with the above messages. It doesnt proceed beyond this

**Comment by jwillemsen** [comment]
What happens when you don't use an ini file?

**Comment by madhugit2022** [comment]
./subscriber -DCPSDebugLevel 5
(423|423) INFO: set_DCPS_debug_level: set to 5
(423|423) NOTICE: not using file configuration - no configuration file specified.
(423|423) Service_Participant::get_domain_participant_factory: This is OpenDDS 3.20.0 using ACE 7.0.8
(423|423) Service_Participant::get_domain_participant_factory: log_level: debug DCPS_debug_level: 5
(423|423) NOTICE: Service_Participant::intializeScheduling() - no scheduling policy specified, not setting policy.
(423|423) Service_Participant::get_domain_participant_factory: Creating LinuxNetworkConfigMonitor
(423|423) Service_Participant::set_repo_ior: Repo[DEFAULT_REPO] == file://repo.ior

./publisher -DCPSDebugLevel 5
(425|425) INFO: set_DCPS_debug_level: set to 5
(425|425) NOTICE: not using file configuration - no configuration file specified.
(425|425) Service_Participant::get_domain_participant_factory: This is OpenDDS 3.20.0 using ACE 7.0.8
(425|425) Service_Participant::get_domain_participant_factory: log_level: debug DCPS_debug_level: 5
(425|425) NOTICE: Service_Participant::intializeScheduling() - no scheduling policy specified, not setting policy.
(425|425) Service_Participant::get_domain_participant_factory: Creating LinuxNetworkConfigMonitor
(425|425) Service_Participant::set_repo_ior: Repo[DEFAULT_REPO] == file://repo.ior

Both publisher and subscriber prints these and doesnt print anything

**Comment by jwillemsen** [comment]
Not sure what happens, we do test regularly OpenDDS as part of AXCIOMA on [Yocto 2.5.3](https://docs.yoctoproject.org/2.5.3/) using a [xilinx ZCU102](https://www.xilinx.com/products/boards-and-kits/ek-u1-zcu102-g.html) target board, there it works, see https://www.axcioma.org/scoreboard.html for the build/test results. We currently use OpenDDS 3.21.0

**Comment by madhugit2022** [comment]
I still get the same issue when I used 3.21.

**Comment by jwillemsen** [comment]
To busy @madhugit2022 to dive into this just for fun, see the [commercial support](https://opendds.org/support.html) options for OpenDDS including @RemedyIT, the company I work for

**Comment by jrw972** [comment]
Is DNS working correctly?

**Comment by madhugit2022** [comment]
hi,

yes. DNS is working correctly. able to ping google.com

**Comment by vermaete** [comment]
@jrw972 Agree to close this one?

* as not active
* not clear what the error is
* In latest meta-opendds the example is working
