### ISSUE TITLE
opendds yocto do_package errer

### ISSUE THREAD

**Issue by cxf-xiao** [OpenDDS/meta-opendds#32]
ERROR: opendds-3.24-r0 do_package: opendds-dev: Multiple shlib providers for libTAO_PortableServer.so.2.5.19: opendds-dev, opendds (used by files: /home/cxf/yocto-real-time-edge/build-imx-real-time-edge/tmp/work/armv8a-poky-linux/opendds/3.24-r0/packages-split/opendds-dev/usr/share/DDS_ROOT/ACE_wrappers/TAO/tao/ImR_Client/libTAO_ImR_Client.so.2.5.19)
ERROR: opendds-3.24-r0 do_package: opendds-dev: Multiple shlib providers for libACE.so.6.5.19: opendds, opendds-dev (used by files: /home/cxf/yocto-real-time-edge/build-imx-real-time-edge/tmp/work/armv8a-poky-linux/opendds/3.24-r0/packages-split/opendds-dev/usr/share/DDS_ROOT/tools/repoctl/repoctl)
ERROR: opendds-3.24-r0 do_package: opendds-dev: Multiple shlib providers for libTAO_IORTable.so.2.5.19: opendds-dev, opendds (used by files: /home/cxf/yocto-real-time-edge/build-imx-real-time-edge/tmp/work/armv8a-poky-linux/opendds/3.24-r0/packages-split/opendds-dev/usr/share/DDS_ROOT/dds/InfoRepo/libOpenDDS_Federator.so.3.24.1)

WARNING: opendds-3.24-r0 do_package_qa: QA Issue: opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/ACE_wrappers/TAO/TAO_IDL/.debug/libTAO_IDL_FE.so.2.5.19
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/ACE_wrappers/TAO/orbsvcs/orbsvcs/.debug/libTAO_Svc_Utils.so.2.5.19
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/ACE_wrappers/TAO/tao/Messaging/.debug/libTAO_Messaging.so.2.5.19
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/ACE_wrappers/TAO/tao/CSD_Framework/.debug/libTAO_CSD_Framework.so.2.5.19
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/ACE_wrappers/TAO/tao/ImR_Client/.debug/libTAO_ImR_Client.so.2.5.19
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/ACE_wrappers/TAO/tao/IORTable/.debug/libTAO_IORTable.so.2.5.19
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/ACE_wrappers/TAO/tao/IORTable/.debug/libTAO_Async_IORTable.so.2.5.19
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/ACE_wrappers/TAO/tao/.debug/libTAO.so.2.5.19
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/ACE_wrappers/TAO/tao/CodecFactory/.debug/libTAO_CodecFactory.so.2.5.19
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/ACE_wrappers/TAO/tao/AnyTypeCode/.debug/libTAO_AnyTypeCode.so.2.5.19
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/ACE_wrappers/TAO/tao/PortableServer/.debug/libTAO_PortableServer.so.2.5.19
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/ACE_wrappers/TAO/tao/Valuetype/.debug/libTAO_Valuetype.so.2.5.19
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/ACE_wrappers/TAO/tao/IORManipulation/.debug/libTAO_IORManip.so.2.5.19
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/ACE_wrappers/TAO/tao/Codeset/.debug/libTAO_Codeset.so.2.5.19
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/ACE_wrappers/TAO/tao/PI/.debug/libTAO_PI.so.2.5.19
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/ACE_wrappers/TAO/tao/BiDir_GIOP/.debug/libTAO_BiDirGIOP.so.2.5.19
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/ACE_wrappers/TAO/tao/DynamicInterface/.debug/libTAO_DynamicInterface.so.2.5.19
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/ACE_wrappers/TAO/tao/CSD_ThreadPool/.debug/libTAO_CSD_ThreadPool.so.2.5.19
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/ACE_wrappers/ace/.debug/libACE.so.6.5.19
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/ACE_wrappers/ace/XML_Utils/.debug/libACE_XML_Utils.so.6.5.19
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/tools/modeling/codegen/model/.debug/libOpenDDS_Model.so.3.24.1
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/dds/monitor/.debug/libOpenDDS_monitor.so.3.24.1
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/dds/FACE/.debug/libOpenDDS_FACE.so.3.24.1
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/dds/.debug/libOpenDDS_Dcps.so.3.24.1
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/dds/InfoRepo/.debug/libOpenDDS_InfoRepoLib.so.3.24.1
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/dds/InfoRepo/.debug/libOpenDDS_InfoRepoServ.so.3.24.1
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/dds/InfoRepo/.debug/libOpenDDS_Federator.so.3.24.1
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/dds/DCPS/RTPS/.debug/libOpenDDS_Rtps.so.3.24.1
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/dds/DCPS/security/.debug/libOpenDDS_Security.so.3.24.1
opendds-dbg: found library in wrong location: /usr/share/DDS_ROOT/dds/DCPS/trans

**Comment by jrw972** [comment]
@vermaete Do you think we can close this issue?

**Comment by vermaete** [comment]
@jrw972 
Well, something in the current recipe about debug packages, shared libraries and sdk is definitely
 wrong.  But fixing it in the MPC build system is probably a lost effort.
On the other hand, I have products with the current version of the recipe that works well.
 I hope I can find some time to work on the cmake flavour of the OpenDDS recipe.

So yes, I would close it because it was silent in this ticket for a few months.
And place our hope one cmake.

**Comment by jrw972** [comment]
Okay.
