### ISSUE TITLE
Missing bblayers.conf

### ISSUE THREAD

**Issue by nirhenn** [OpenDDS/meta-opendds#33]
Hi,

trying to build with Yocto and while trying to add the layer to my build env I get that unable to find bblayers.conf 

what am I doing wrong?

**Comment by mitza-oci** [comment]
I'm not sure, please provide some more information including the versions and configurations of all relevant software components.

**Comment by vermaete** [comment]
It look OK for me:

```
git clone git://git.yoctoproject.org/poky -b kirkstone
cd poky/
git clone https://github.com/OpenDDS/meta-opendds.git -b kirkstone
. oe-init-build-env 
bitbake-layers add-layer ../meta-opendds
```

`cat conf/bblayers.conf`


```
# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/jan/projects/poky/meta \
  /home/jan/projects/poky/meta-poky \
  /home/jan/projects/poky/meta-yocto-bsp \
  /home/jan/projects/poky/meta-opendds \
  "
```

Could you elaborate on your findings?
Or close the issue?

**Comment by vermaete** [comment]
@mitza-oci Could we close this older ticket?

**Comment by nirhenn** [comment]
YesThx,NirSent from my iPhoneOn 21 Apr 2024, at 17:23, Jan Vermaete ***@***.***> wrote:﻿
@mitza-oci Could we close this older ticket?
